# name: CI/CD Pipeline

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build-test-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: "3.9"

#     - name: Install dependencies
#       run: pip install -r requirements.txt

#     - name: Train Model
#       run: python train.py

#     - name: Run Tests
#       run: pytest tests/

#     - name: Build Docker Image
#       run: docker build -t ml-model-app:latest .

#     - name: Deploy (Simulated)
#       run: |
#         echo "Simulated Deployment - running container"
#         docker run -d -p 8000:8000 ml-model-app:latest

name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train Model
      run: python train.py
    
    - name: Install package
      run: pip install -e .

    - name: Run Tests
      run: pytest tests/

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/ml-model-app
        docker build -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest

    - name: Deploy (Simulated)
      run: |
        echo "🚀 Deployment simulated: container pushed to DockerHub."
        echo "You can pull and run it locally with:"
        echo "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ml-model-app:latest"
        echo "docker run -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/ml-model-app:latest"
